create table products (
  id          integer generated by default as identity constraint products_pkey primary key,
  brand       varchar(25),
  model       varchar(25),
  price       numeric(19, 2),
  amount      integer,
  description varchar(255)
);

alter table products owner to postgres;



